  options:
    logging: CLOUD_LOGGING_ONLY
  steps:
  # Run tests
  - id: 'Run tests'
    name: 'node:20'
    env:
      - DIRECT_URL=direct_url
      - DATABASE_URL=database_url
      - ENVIRONMENT=test
      - JWT_AUTH_TOKEN_SECRET=jwt_auth_token_secret
      - JWT_AUTH_TOKEN_EXPIRES_IN=5h
      - JWT_REFRESH_TOKEN_SECRET=jwt_refresh_token_secret
      - JWT_REFRESH_TOKEN_EXPIRES_IN=1w
      - DOMAIN=localhost
      - ADMIN_PASSWORD=admin
    script: |
      #!/usr/bin/env bash
      npm install --global pnpm@8.5.1
      pnpm install
      pnpm test
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--build-arg', 'WEB_APP_BRANCH=$BRANCH_NAME', '--build-arg', 'VITE_API_URL=/api', '-t', 'gcr.io/$PROJECT_ID/github.com/edge33/sibarifly-dashboard:$BRANCH_NAME', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/github.com/edge33/sibarifly-dashboard:$BRANCH_NAME']
  # Run database migrations
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: npx
    env:
     - DIRECT_URL=$_DIRECT_URL
     - DATABASE_URL=$_DATABASE_URL
    args:
      - 'prisma'
      - 'migrate'
      - 'deploy'
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'sibarifly-dashboard-$BRANCH_NAME'
    - '--image'
    - 'gcr.io/$PROJECT_ID/github.com/edge33/sibarifly-dashboard:$BRANCH_NAME'
    - '--region'
    - 'europe-west8'
    - '--allow-unauthenticated'
  images:
  - 'gcr.io/$PROJECT_ID/github.com/edge33/sibarifly-dashboard:$BRANCH_NAME'

