name: Ping Supabase to Prevent Pausing

on:
  schedule:
    - cron: '0 9 * * 1,4' # 9:00 AM UTC every Monday and Thursday
  workflow_dispatch: # Manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev]
    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Supabase Client
        run: npm install @supabase/supabase-js --force

      - name: Ping Supabase (${{ matrix.environment }})
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TEST_VAR: ${{ secrets.TEST_VAR }}
        run: |
          node -e "
          (async () => {
            try {
              console.log('testing', process.env.TEST_VAR)
              const { createClient } = require('@supabase/supabase-js');
              const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);

              const { data, error } = await supabase.from('event').select('*').limit(10);
              if (error) throw error;

              console.log('Ping successful');
            } catch (err) {
              console.error('Error pinging Supabase:', err.message);
              process.exit(1);
            }
          })();
          "
